language: ruby
rvm:
 - 1.9.3
sudo: required

install:
  - bundle install --path vendor/bundle

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash"

script:
- FOSSA_API_KEY=3c97524e0e919530bbc6431f2ef2b70f fossa
