language: ruby
rvm:
 - 2.2
sudo: required

install:
  - bundle install

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash"

script:
- FOSSA_API_TOKEN=3c97524e0e919530bbc6431f2ef2b70f fossa
